Staging
greenfox-academy/maw-sit-sit-poker-backend pull request #10
Opened 2017-06-29 15:10 UTC by gaborki

2017-07-03 12:44 UTC, kondfox requested changes

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/aspect/AuthorizationAspect.java
> +      "&& !@annotation(com.greenfox.poker.service.Accessible)")
You could create pointcut variables and use just their names here in this condition.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/aspect/AuthorizationAspect.java
> +      return joinPoint.proceed();
That doesn't seem so nice. It smells, I have to think more about it why.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/aspect/AuthorizationAspect.java
> +          System.out.println(requestHeader.value() + " = " + argsList[argIndex]);
You shouldn't have such debugging code parts in your production code.
We should refactor these in a next iteration to log these informations with a proper logging service instead of these custom `sout`s.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +  public GamesList getGamesList() {
This should be a ResponseEntity as well with proper status code.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +  @Accessible
According to today's standup, this endpoint shouldn't be accessible without a valid token.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +  public ResponseEntity<?> updateGameState(@PathVariable("id") long gameId, @RequestBody @Valid PlayerAction action, BindingResult bindingResult, @RequestHeader("X-poker-token") String token){
styling: format this line to multiple lines

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +    if (!gameService.isGameExistById(gameId)) { return new ResponseEntity(errorMessageService.responseToWrongGameId(), HttpStatus.NOT_FOUND);
styling: the return should be in a new line.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +  PokerUser pokerUser;
You should use your PokerUserDTO model here instead of your PokerUser.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +  private List<Long> playerIdNumbersAroundTheTable = new ArrayList<>();
maybe `playerIds` are shorter and not much less understandable than `playerIdNumbersAroundTheTable`.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +  private List<Long> playerIdNumbersAroundTheTable = new ArrayList<>();
and do the initialization in the constructor instead of the field.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +  public HashMap<Long, GameState> getGameStateMap() {
don't use the implementation type (Map) in the names, because it could change tomorrow, and you don't want to rename your method everywhere then.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameStateService.java
> +    Betting betting = new Betting(gameService);
woah! never pass a service in an argument! :)

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameStateService.java
> +  BettingCycleInEachRound bettingCycleInEachRound = new BettingCycleInEachRound(gameService);
woah! never pass a service in an argument! :)

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +  private void removeGamePlayersFromTableWithLessChipsThankBigBlind(long gameStateId) {
If you would pass the GameState object itself in the argument, you could save the `gameState = gameService.getGameStateMap().get(gameStateId);` calls in all your methods, which would be better.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +      gameState.setRound(Round.IDLE);
You shouldn't mix functionalities. From your function name I assume a boolean method that checks the named statement. Here you are setting the game state above the checking.
It's better if you separate this to different methods.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +              findNextPlayerIdAtTheTable(gameStateId, gameState.getDealerPlayerId()));
If you would pass the Gamestate object itself, one argument would be enough.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +      gameState.setDealerPlayerId(gameState.getPlayers().get(0).getId());
It's better if you create a function for getting the first player: `gameState.getPlayers().get(0).getId()`.
The reason is that if you later needs to change the format of your Players list from ArrayList to something different, it will be easier to find and change the way of fetching an element from it if you have a separate function for this purpose.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +    }
You should create a separate function to get all the players around the table.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +    }
And don't mix functionalities. Your players list should be updated whenever a new player joins a table or a player leaves it. But it's unnecessary to update the list here.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +    return playerIdNumbersAroundTheTable.get(indexOfCurrentPlayerId + 1);
I wrote above that you should create a separate function to get the first player of the table.
Here - when I see that you use this fetching other players as well than the first player - I would say that this recommended function should be more general: it should be able to provide the n-th element of your players list.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +    bigBlindPlayerId = findNextPlayerIdAtTheTable(gameStateId, smallBlindPlayerId);
Maybe it worth to track who is the big blind and the small blind in the Gamestate to keep  these functions simple. Of course in this case you shouldn't send these fields to the frontend.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +        gameState.setPot(gameState.getPot() + smallBlindAmount);
Code duplication. You are using the same functions a few lines below, but with a different value.
This means that it worth a separate function :)

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +    gameState.setActorPlayerId(findNextPlayerIdAtTheTable(gameStateId, bigBlindPlayerId));
Don't mix functionalities. You shouldn't set the actor here, it doesn't belong to this function.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +  private GamePlayerHand gamePlayerHand;
Beside the services none of these fields belongs here :)
You should be able to reach this data in different ways.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +  private void shuffleDeck(long gameStateId) {
You shouldn't need this function here.
You already have a shuffling function in your DeckService. Use that.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +  }
This method could be much more simple. Don't overcomplicate it, just do what you say in the name of your method ;)

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/BettingCycleInEachRound.java
> +    bettingRound = 0;
What does it mean? :)

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/BettingCycleInEachRound.java
> +  public void bettingCycle(long gameStateId) {
This is exactly the same function as the one above.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/BettingCycleInEachRound.java
> +  private void createActiveGamePlayersListAroundTheTableStartingFromFirstToAct(long gameStateId) {
This method should be more simple and it should return with the active players instead of setting a field of this class.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/BettingCycleInEachRound.java
> +  //todo
there shouldn't be todo comments in the production code :)

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/BettingCycleInEachRound.java
> +  }
This function doesn't do anything, so it shouldn't be here.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Flop.java
> +  public void initForBettingGameState(long gameStateId){
hm? betting in flop?

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Flop.java
> +  private void getFlopThreeCards(long gameStateId) {
If the name of your function is `get~`, I assume that it returns with the data you are getting.
Don't name a setting function as a "get".

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Idle.java
> +  public void checkForPlayersNumberToStartTheGame() {
Again: the naming is not correct here.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/Idle.java
> +  public void checkForPlayersNumberToStartTheGame() {
And basically it's not good that you call your `Betting`, `Flop` and other game states from your service AND you call your service vica versa from your states. The calling flow should be a one way flow.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/gamestates/River.java
> +    getRiverCard(gameStateId);
If your function is just another function, than one is probably enough :)

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/model/Deck.java
> +  private static final AtomicInteger totalDeckCounter = new AtomicInteger(0);
Your id is `long`, so use AtomicLong instead of AtomicInteger.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/model/GamePlayerHand.java
> +  private List<Card> gamePlayerOwnTwoCards;
Give this a better and shorter name.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/model/GameState.java
> +  private List<GamePlayerHand> gamePlayerHandList;
Instead of a list here, this could be a GamePlayerHand field in the GamePlayer object with a JsonIgnore annotation. It makes sense to store this there.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/model/GameState.java
> +  private List<GamePlayerHand> gamePlayerHandList;
In that case you don't even need an id for your hand.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/DeckService.java
> +//  }
You shouldn't have outcommented code parts in your production code.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/DtoService.java
> +  public boolean hasPlayerEnoughChipsToPlay(long chipsToPlayWith, long userId){
This method doesn't belong here, it's a DTO service. The purpose if this service is to convert Entity objects to DTOs and backward.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/DtoService.java
> +  public void deductChipsFromAvailableChips(long chipsToPlayWith, long playerId){
This doesn't belong to here either.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +  private HashMap<Long, GameState> gameStateMap = new HashMap<>();
The type of the implementation ("Map") shouldn't be in the name if the variable, because the implementation could change later.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +    gameRepo.save(newGame);
Hm? Why do you create an exactly same game from an existing game?

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +    GamesList gamesList = new GamesList();
Your goal is to get an existing list here.
So you should solve this without any new object creation.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +    return (gameRepo.exists(id));
Unnecessary brackets here.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +            return true;
There's a more simpler way to check this than looping through the whole list.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +    PokerUserDTO player = dtoService.userDTOHashMap.get(playerId);
`dtoService.userDTOHashMap`?

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +        playersAtTable.remove(player);
You shouldn't loop through your whole list to find the player.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +    return new StatusError("success", playerName + " left game: " + gameName);
You should separate the "leave game" logic from the response you send after a successful leaving.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +        index = playersAtTable.indexOf(player);
Again: don't loop to find an id.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +  public void updateGame(long playerId, long gameId, PlayerAction playerAction){
This is a function where you do a lot of different things.
Separate the contents below to separate, well described functions that do just one thing.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameStateService.java
> +    bettingCycleInEachRound.bettingCycle(gameStateId);
You are calling the same two functions at the end of all your functions here.
This is duplication.
There should be a better way to solve this.

2017-07-03 12:44 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/UserService.java
>      List<PokerUserDTO> topTenDTO = new ArrayList<>();
Top ten what? :)
Top ten list means that you have 10 lists.
And what does the DTO represent?
Give better names here.

2017-07-03 15:40 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/aspect/AuthorizationAspect.java
> +      "&& !@annotation(com.greenfox.poker.service.Accessible)")
I already did just after pull request:)

2017-07-04 07:30 UTC, gaborki commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +  public GamesList getGamesList() {
done

2017-07-04 07:30 UTC, gaborki commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +  public ResponseEntity<?> updateGameState(@PathVariable("id") long gameId, @RequestBody @Valid PlayerAction action, BindingResult bindingResult, @RequestHeader("X-poker-token") String token){
done

2017-07-04 07:31 UTC, gaborki commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +    if (!gameService.isGameExistById(gameId)) { return new ResponseEntity(errorMessageService.responseToWrongGameId(), HttpStatus.NOT_FOUND);
done

2017-07-04 07:33 UTC, gaborki commented on src/main/java/com/greenfox/poker/service/GameService.java
> +  private HashMap<Long, GameState> gameStateMap = new HashMap<>();
done

2017-07-04 07:33 UTC, gaborki commented on src/main/java/com/greenfox/poker/service/GameService.java
> +  public HashMap<Long, GameState> getGameStateMap() {
done

2017-07-04 07:34 UTC, gaborki commented on src/main/java/com/greenfox/poker/service/GameService.java
> +    return (gameRepo.exists(id));
done

2017-07-04 07:44 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +  private List<Long> playerIdNumbersAroundTheTable = new ArrayList<>();
done

2017-07-04 08:33 UTC, gaborki commented on src/main/java/com/greenfox/poker/service/GameService.java
> +            return true;
done

2017-07-04 09:29 UTC, gaborki commented on src/main/java/com/greenfox/poker/service/GameService.java
> +        playersAtTable.remove(player);
done

2017-07-04 09:33 UTC, gaborki commented on src/main/java/com/greenfox/poker/service/GameService.java
> +    return new StatusError("success", playerName + " left game: " + gameName);
done

2017-07-04 09:43 UTC, gaborki commented on src/main/java/com/greenfox/poker/service/GameService.java
> +        index = playersAtTable.indexOf(player);
done

2017-07-04 09:55 UTC, gaborki commented on src/main/java/com/greenfox/poker/service/GameService.java
> +  public void updateGame(long playerId, long gameId, PlayerAction playerAction){
done..(?)

2017-07-04 11:40 UTC, gaborki commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +  @Accessible
done

2017-07-04 14:36 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +  private GamePlayerHand gamePlayerHand;
done

2017-07-04 14:36 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +  private void removeGamePlayersFromTableWithLessChipsThankBigBlind(long gameStateId) {
done

2017-07-04 14:36 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +      gameState.setRound(Round.IDLE);
done

2017-07-04 14:36 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +              findNextPlayerIdAtTheTable(gameStateId, gameState.getDealerPlayerId()));
done

2017-07-04 14:37 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +      gameState.setDealerPlayerId(gameState.getPlayers().get(0).getId());
done

2017-07-04 14:37 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +    }
other method used

2017-07-04 14:37 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +    return playerIdNumbersAroundTheTable.get(indexOfCurrentPlayerId + 1);
other method used

2017-07-04 14:37 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +    bigBlindPlayerId = findNextPlayerIdAtTheTable(gameStateId, smallBlindPlayerId);
done

2017-07-04 14:39 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +        gameState.setPot(gameState.getPot() + smallBlindAmount);
other way but solved

2017-07-04 14:39 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +    gameState.setActorPlayerId(findNextPlayerIdAtTheTable(gameStateId, bigBlindPlayerId));
done

2017-07-04 14:39 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +  private void shuffleDeck(long gameStateId) {
done

2017-07-04 14:39 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Betting.java
> +  }
done

2017-07-04 14:40 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/service/GameStateService.java
> +  BettingCycleInEachRound bettingCycleInEachRound = new BettingCycleInEachRound(gameService);
done

2017-07-04 14:40 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/service/GameStateService.java
> +    Betting betting = new Betting(gameService);
done

2017-07-04 14:40 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/service/GameStateService.java
> +    bettingCycleInEachRound.bettingCycle(gameStateId);
done

2017-07-04 14:41 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/BettingCycleInEachRound.java
> +    bettingRound = 0;
done in an elegant way

2017-07-04 14:41 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/BettingCycleInEachRound.java
> +  public void bettingCycle(long gameStateId) {
done

2017-07-04 14:41 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/BettingCycleInEachRound.java
> +  private void createActiveGamePlayersListAroundTheTableStartingFromFirstToAct(long gameStateId) {
done

2017-07-04 14:41 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/BettingCycleInEachRound.java
> +  //todo
done

2017-07-04 14:41 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/BettingCycleInEachRound.java
> +  }
done

2017-07-04 14:42 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Flop.java
> +  public void initForBettingGameState(long gameStateId){
done

2017-07-04 14:42 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Flop.java
> +  private void getFlopThreeCards(long gameStateId) {
done

2017-07-04 14:43 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/Idle.java
> +  public void checkForPlayersNumberToStartTheGame() {
done

2017-07-04 14:43 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/gamestates/River.java
> +    getRiverCard(gameStateId);
done

2017-07-04 14:43 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/model/Deck.java
> +  private static final AtomicInteger totalDeckCounter = new AtomicInteger(0);
long

2017-07-04 14:44 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/model/Deck.java
> +  private static final AtomicInteger totalDeckCounter = new AtomicInteger(0);
i mean done

2017-07-04 14:44 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/model/GamePlayerHand.java
> +  private List<Card> gamePlayerOwnTwoCards;
done

2017-07-04 14:45 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/service/DeckService.java
> +//  }
done

2017-07-04 15:02 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/model/GameState.java
> +  private List<GamePlayerHand> gamePlayerHandList;
done

2017-07-14 08:24 UTC, kondfox approved these changes

2017-07-14 08:55 UTC, merged