Stage
greenfox-academy/maw-sit-sit-poker-backend pull request #9
Opened 2017-06-22 07:38 UTC by lengyelnorbert

please accept it

2017-06-22 09:11 UTC, kondfox requested changes

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +      long currentStateId = gameService.getGamebyId(id).getGamestate_id();
1. Move this logics to the service layer as well.
2. Styling: instead of `getGamestate_id()` use camalCase namings like `getGamestateId()`

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +    long gameStateId = game.getGamestate_id();
Move this logics to your service layer.

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/controller/HomeController.java
> +    System.out.println(newDeckToTestHere);
1. You have `;;` - double semicolons in line 23.
2. The production code base shouldn't contain any debugging code parts like this one. So please remove these lines from the code that you'd like to merge to master.

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/model/Game.java
> +  private Integer currentPlayers;
According to our current specification, we don't need the `currentPlayers` field anymore.
Remove this.

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/model/Game.java
> +    return gamestate_id;
camelCase

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/model/Game.java
> +    this.gamestate_id = gamestate_id;
camelCase

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/model/PokerUserDTO.java
> +public class PokerUserDTO implements ResponseType{
Missing space before `{`

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/model/StatusError.java
> +public class StatusError implements ResponseType{
missing space before `{`

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/repository/PokerUserRepo.java
> +  boolean existsByUsername(String username);
nice!

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/DeckService.java
> +    return deck;
It works, but you don't even need to return with the deck. This could be a void method as well, which would be better.

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +    }
There should be an easier way to get a Gamestate from a collection other then looping through all the list.
Refactor this one.

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/TokenService.java
> +  }
I think your `getPokerUserFromToken(String token)` method should be enough for you.
The `getUsernameFromToken(String token)` and `getIdFromToken(String token)` methods are just unnecessary duplications which you should remove.

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/UserService.java
> +  public ResponseType respondToMissingParameters(BindingResult bindingResult) {
That method is OK right now, but don't be surprised if we'll refactor this later.

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/UserService.java
> +    if (users.size() > 0 && users.get(0).getPassword().equals(loginRequest.getPassword())){
For sake of easier debugging, please separate this method to multiple lines.
Get the size of your users list,
get the password,
and then compare these in this condition.

2017-06-22 09:11 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/UserService.java
> +    pokerUserDTO.setChips(pokerUser.getChips());
You should have a method for this purpose in your service layer which converts a PokerUser object to a PokerUserDTO object.

2017-06-22 09:11 UTC, kondfox commented on src/test/java/com/greenfox/poker/controller/UserControllerTest.java
> +    testPokerUser.setEmail("jeno@kovacs.hu");
Let's talk about this during our meeting today.

2017-06-22 09:27 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +    long gameStateId = game.getGamestate_id();
This is under construction, Gábor mentioned he will totally change it

2017-06-22 09:32 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/controller/HomeController.java
> +    System.out.println(newDeckToTestHere);
Done

2017-06-22 09:33 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/model/Game.java
> +  private Integer currentPlayers;
Done

2017-06-22 09:37 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/model/Game.java
> +    return gamestate_id;
Done

2017-06-22 09:37 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/model/Game.java
> +    this.gamestate_id = gamestate_id;
Done

2017-06-22 09:38 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/model/PokerUserDTO.java
> +public class PokerUserDTO implements ResponseType{
Done

2017-06-22 09:38 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/model/StatusError.java
> +public class StatusError implements ResponseType{
Done

2017-06-22 09:43 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/service/DeckService.java
> +    return deck;
Done

2017-06-22 09:50 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/service/TokenService.java
> +  }
`getIdFromToken(String token) ` is being used inside the `getPokerUserFromToken(String token)`.
But You maybe right about `getUsernameFromToken(String token)`

2017-06-22 09:53 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/service/UserService.java
> +  public ResponseType respondToMissingParameters(BindingResult bindingResult) {
So I don't touch it for now

2017-06-22 10:05 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/service/UserService.java
> +    if (users.size() > 0 && users.get(0).getPassword().equals(loginRequest.getPassword())){
Done

2017-06-22 10:25 UTC, RaminShamsi commented on src/main/java/com/greenfox/poker/service/UserService.java
> +    pokerUserDTO.setChips(pokerUser.getChips());
Done

2017-06-23 08:54 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +      long currentStateId = gameService.getGamebyId(id).getGamestate_id();
done

2017-06-23 08:54 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/controller/GameController.java
> +    long gameStateId = game.getGamestate_id();
done

2017-06-23 08:55 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/controller/HomeController.java
> +    System.out.println(newDeckToTestHere);
done

2017-06-23 08:59 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/model/Game.java
> +  private Integer currentPlayers;
deleted from object and from db table as well

2017-06-23 09:06 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/model/Game.java
> +    this.gamestate_id = gamestate_id;
changed in object and column added to db as well

2017-06-23 09:07 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/model/PokerUserDTO.java
> +public class PokerUserDTO implements ResponseType{
done

2017-06-23 09:08 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/model/StatusError.java
> +public class StatusError implements ResponseType{
done

2017-06-23 09:12 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/service/DeckService.java
> +    return deck;
done

2017-06-23 09:26 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/service/GameService.java
> +    }
solved with HashMap but pls have a look on it as I havent worked wish hashmaps before

2017-06-23 09:28 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/service/TokenService.java
> +  }
I didnt touch this one as Ramin had some questions about it and he was dealing the most with the tokens...

2017-06-23 09:30 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/service/UserService.java
> +    if (users.size() > 0 && users.get(0).getPassword().equals(loginRequest.getPassword())){
it was done

2017-06-23 13:28 UTC, kondfox approved these changes
But fix my comments.

2017-06-23 13:28 UTC, kondfox commented on src/main/java/com/greenfox/poker/controller/UserController.java
> +        return new ResponseEntity(userService.registerWithOccupiedUsername(), HttpStatus.CONFLICT);
Wrong indentation.

2017-06-23 13:28 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/Access.java
> +
unnecessary extra line here.

2017-06-23 13:28 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/GameService.java
> +  public GameState getGameState(long id) {
private

2017-06-23 13:28 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/TokenService.java
> +  }
ok

2017-06-23 13:28 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/UserService.java
> +    List<PokerUser> users = pokerUserRepo.findByUsername(loginRequest.getUsername());
username is unique, so this should be just one object instead of a list.

2017-06-23 13:28 UTC, kondfox commented on src/main/java/com/greenfox/poker/service/UserService.java
> +  public long getUserIdFromUsername(String username) {
why do you need that? I guess you shouldn't need this.

2017-06-23 13:28 UTC, kondfox commented on src/test/java/com/greenfox/poker/service/DeckServiceTest.java
> +    createTestDeckAndCardsList();
Could be in `@Before`

2017-06-23 13:28 UTC, kondfox commented on src/test/java/com/greenfox/poker/service/DeckServiceTest.java
> +
It's empty now.

2017-06-23 13:28 UTC, kondfox commented on src/test/java/com/greenfox/poker/service/GameServiceTest.java
> +    assertEquals(1, 1);
??

2017-06-23 13:29 UTC, merged

2017-06-26 07:57 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/controller/UserController.java
> +        return new ResponseEntity(userService.registerWithOccupiedUsername(), HttpStatus.CONFLICT);
done

2017-06-26 07:57 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/service/Access.java
> +
done

2017-06-26 07:57 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/service/GameService.java
> +  public GameState getGameState(long id) {
done

2017-06-26 08:25 UTC, lengyelnorbert commented on src/main/java/com/greenfox/poker/service/UserService.java
> +    List<PokerUser> users = pokerUserRepo.findByUsername(loginRequest.getUsername());
done

2017-06-26 08:29 UTC, lengyelnorbert commented on src/test/java/com/greenfox/poker/service/DeckServiceTest.java
> +    createTestDeckAndCardsList();
done

2017-06-26 08:29 UTC, lengyelnorbert commented on src/test/java/com/greenfox/poker/service/DeckServiceTest.java
> +
working on it

2017-06-26 08:29 UTC, lengyelnorbert commented on src/test/java/com/greenfox/poker/service/GameServiceTest.java
> +    assertEquals(1, 1);
working on it as well :)